---
- hosts: localhost

  roles:
    # setup the common environment files
    - role: '../dotfiles'

    # setup the homebrew, caskroom, gems configuration
    - role: osx.homebrew
      when: ansible_distribution == 'MacOSX'


  tasks:

    - meta: flush_handlers

    - name: install applications from Brewfile
      debug: msg='nope'
      
    - name: install configurations from mackup
      debug: msg='nope1'