---
- hosts: localhost

  roles:
    # setup the common environment files
    - role: '../dotfiles'

    # setup the homebrew, caskroom, gems configuration
    - role: osx.homebrew
      when: ansible_distribution == 'MacOSX'

  tasks:

    - meta: flush_handlers

    # install all Brew apps
    - name: copy over Brewfile
      copy: src=files/Brewfile dest=/tmp/Brewfile
      register: brewfile
      
    - name: install applications from Brewfile
      shell: brew brewdle chdir=/tmp/
      when: brewfile.changed

    # configure all osx defaults
    # configure zsh
    # configure dropbox