---

- name: Are brew-cask environment variables set?
  stat: path=/Users/mahmoud/.common_env/sourceable_99_cask.sh
  register: cask_env_set

- name: Set brew-cask environment variable if cask doesn't exist
  copy: content=''
        dest=/Users/mahmoud/.common_env/sourceable_99_cask.sh
  when: cask_env_set.stat.exists == false

- name: add cask opts as a sourced file in common_env
  lineinfile: dest=/Users/mahmoud/.common_env/sourceable_99_cask.sh
              regexp='^export HOMEBREW_CASK_OPTS'
              line='export HOMEBREW_CASK_OPTS="--appdir=/Applications"'
              state=present

